---
- name: create multiple users in node
  hosts: all
  become: true
  tasks:
    - name: add a list of users
      user: name='{{ item }}' state=present
      with_items:
        - Raj
        - Sai
        - Hari
