---
- name: Installing https and starting the service
  hosts: webservers
  become: yes
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: installed

  - name: Start httpd service
    service:
      name: httpd
      state: started

