---
- name: Aache Tomcat Installation Setup
  hosts: webservers
  become: true
  tasks:
  - name: install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Download tomcat packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz
      dest: /opt
  
  - name: Extract the tar file
    unarchive:
      src: /opt/apache-tomcat-8.5.82.tar.gz
      dest: /opt
      remote_src: yes

  - name: execute startup.sh service give execution permission
    file:
      path: /opt/apache-tomcat-8.5.82/bin/startup.sh
      mode: 0777

  - name: starttomcat service
    shell: nohup ./startup.sh   #nohup --> to run continuously
    args:
      chdir: /opt/apache-tomcat-8.5.82/bin


    
